import React from "react";
import {
  PccOperationsIcon,
  PccSecurityIcon,
  PccIamIcon,
  PccSubscriptionsIcon,
  PccEntitlementsIcon,
  PccBillingIcon,
  PccKeysIcon,
  PccTrafficIcon,
  PccComplianceIcon,
  PccThreatsIcon,
  PccMobileIcon,
  PccDesktopIcon,
  PccConfigIcon,
  PccDevelopersIcon,
  PccKnowledgeIcon,
  PccAnalyticsIcon,
  PccMarketplaceIcon,
  PccTenantsIcon,
  PccInfrastructureIcon,
  PccIntegrationsIcon,
  PccAiIcon,
  PccSupportIcon,
  type PccIconProps,
} from "@/components/home/icons/PccIcons";

export type PccDomainCluster = "ops" | "security" | "iam" | "billing" | "dev" | "support";

export interface PccDomainEntry {
  id: string;
  pccCode: string;
  title: string;
  shortTitle: string;
  description: string;
  href: string;
  cluster: PccDomainCluster;
  clusterName: string;
  accentVar: string;
  accentHoverVar: string;
  accentSubtleVar: string;
  accentGlowVar: string;
  permission: string;
  shortcut: string;
  badge?: string | number;
  icon: React.ComponentType<PccIconProps>;
}

export const PCC_CLUSTERS: Record<PccDomainCluster, { name: string; description: string; accentVar: string }> = {
  ops: {
    name: "Core Operations & Fleet",
    description: "Infrastructure telemetry, compute runtime, API traffic, and incident response.",
    accentVar: "--pcc-accent-ops",
  },
  security: {
    name: "Security, Trust & Secrets",
    description: "Tenant isolation barriers, ABAC policy enforcement, compliance, and threat feeds.",
    accentVar: "--pcc-accent-security",
  },
  iam: {
    name: "Identity, Tenants & Config",
    description: "Enterprise tenant directory, SCIM directories, runtime flags, and access governance.",
    accentVar: "--pcc-accent-iam",
  },
  billing: {
    name: "Monetization & Licenses",
    description: "Usage billing, pricing catalogs, subscription lifecycles, and cryptographic keys.",
    accentVar: "--pcc-accent-billing",
  },
  dev: {
    name: "Ecosystem & Developer Tools",
    description: "Developer portal, extension marketplace, third-party connectors, and AI models.",
    accentVar: "--pcc-accent-dev",
  },
  support: {
    name: "Support, Learning & Analytics",
    description: "Executive dashboards, diagnostic telemetry, support queues, and knowledge base.",
    accentVar: "--pcc-accent-support",
  },
};

export const PCC_REGISTRY: PccDomainEntry[] = [
  // Cluster 1: Core Operations & Fleet (Blue)
  {
    id: "operations",
    pccCode: "PCC-01",
    title: "Platform Operations & Fleet",
    shortTitle: "Operations",
    description: "System health, Kubernetes pod fleet, active incidents war room, and deployment pipelines.",
    href: "/ops",
    cluster: "ops",
    clusterName: "Core Operations & Fleet",
    accentVar: "var(--pcc-accent-ops)",
    accentHoverVar: "var(--pcc-accent-ops-hover)",
    accentSubtleVar: "var(--pcc-accent-ops-subtle)",
    accentGlowVar: "var(--pcc-accent-ops-glow)",
    permission: "pcc.ops.view",
    shortcut: "O",
    icon: PccOperationsIcon,
  },
  {
    id: "infrastructure",
    pccCode: "PCC-19",
    title: "Cloud Infrastructure",
    shortTitle: "Infrastructure",
    description: "Kubernetes node clusters, multi-region database replicas, Redis caches, and cloud provider health.",
    href: "/ops",
    cluster: "ops",
    clusterName: "Core Operations & Fleet",
    accentVar: "var(--pcc-accent-ops)",
    accentHoverVar: "var(--pcc-accent-ops-hover)",
    accentSubtleVar: "var(--pcc-accent-ops-subtle)",
    accentGlowVar: "var(--pcc-accent-ops-glow)",
    permission: "pcc.ops.view",
    shortcut: "R",
    icon: PccInfrastructureIcon,
  },
  {
    id: "api-traffic",
    pccCode: "PCC-08",
    title: "API Gateway & Traffic",
    shortTitle: "API Traffic",
    description: "Envoy/Kong rate limiting policies, endpoint deprecation timeline, and circuit breaker telemetry.",
    href: "/api-traffic",
    cluster: "ops",
    clusterName: "Core Operations & Fleet",
    accentVar: "var(--pcc-accent-ops)",
    accentHoverVar: "var(--pcc-accent-ops-hover)",
    accentSubtleVar: "var(--pcc-accent-ops-subtle)",
    accentGlowVar: "var(--pcc-accent-ops-glow)",
    permission: "pcc.traffic.view",
    shortcut: "T",
    icon: PccTrafficIcon,
  },
  {
    id: "desktop-operations",
    pccCode: "PCC-12",
    title: "Desktop Client Operations",
    shortTitle: "Desktop",
    description: "Tauri/Electron cross-platform binaries, auto-update rings, and Apple notarization workflows.",
    href: "/desktop-operations",
    cluster: "ops",
    clusterName: "Core Operations & Fleet",
    accentVar: "var(--pcc-accent-ops)",
    accentHoverVar: "var(--pcc-accent-ops-hover)",
    accentSubtleVar: "var(--pcc-accent-ops-subtle)",
    accentGlowVar: "var(--pcc-accent-ops-glow)",
    permission: "pcc.desktop.view",
    shortcut: "D",
    icon: PccDesktopIcon,
  },

  // Cluster 2: Security, Trust & Secrets (Emerald)
  {
    id: "security",
    pccCode: "PCC-02",
    title: "Security & Tenant Isolation",
    shortTitle: "Security",
    description: "Multi-tenant boundary isolation, ABAC rule evaluation simulator, and PostgreSQL RLS policies.",
    href: "/security/policies",
    cluster: "security",
    clusterName: "Security, Trust & Secrets",
    accentVar: "var(--pcc-accent-security)",
    accentHoverVar: "var(--pcc-accent-security-hover)",
    accentSubtleVar: "var(--pcc-accent-security-subtle)",
    accentGlowVar: "var(--pcc-accent-security-glow)",
    permission: "pcc.security.view",
    shortcut: "S",
    icon: PccSecurityIcon,
  },
  {
    id: "keys-secrets",
    pccCode: "PCC-07",
    title: "Keys & Secrets Vault",
    shortTitle: "Keys & Secrets",
    description: "KMS master keys, mTLS certificate timeline, automatic secret rotation, and dynamic leases.",
    href: "/keys-secrets",
    cluster: "security",
    clusterName: "Security, Trust & Secrets",
    accentVar: "var(--pcc-accent-security)",
    accentHoverVar: "var(--pcc-accent-security-hover)",
    accentSubtleVar: "var(--pcc-accent-security-subtle)",
    accentGlowVar: "var(--pcc-accent-security-glow)",
    permission: "pcc.keys.view",
    shortcut: "K",
    icon: PccKeysIcon,
  },
  {
    id: "compliance",
    pccCode: "PCC-09",
    title: "Compliance & SOC 2",
    shortTitle: "Compliance",
    description: "SOC 2 Type II audit controls, HIPAA/GDPR policies, automated evidence collector, and audit exports.",
    href: "/security/compliance",
    cluster: "security",
    clusterName: "Security, Trust & Secrets",
    accentVar: "var(--pcc-accent-security)",
    accentHoverVar: "var(--pcc-accent-security-hover)",
    accentSubtleVar: "var(--pcc-accent-security-subtle)",
    accentGlowVar: "var(--pcc-accent-security-glow)",
    permission: "pcc.compliance.view",
    shortcut: "C",
    icon: PccComplianceIcon,
  },
  {
    id: "threats",
    pccCode: "PCC-10",
    title: "Threat Intelligence & SOC",
    shortTitle: "Threat Intel",
    description: "Real-time security telemetry, IP blocklists, anomaly intrusion detection, and SIEM feeds.",
    href: "/security/threats",
    cluster: "security",
    clusterName: "Security, Trust & Secrets",
    accentVar: "var(--pcc-accent-security)",
    accentHoverVar: "var(--pcc-accent-security-hover)",
    accentSubtleVar: "var(--pcc-accent-security-subtle)",
    accentGlowVar: "var(--pcc-accent-security-glow)",
    permission: "pcc.threats.view",
    shortcut: "H",
    icon: PccThreatsIcon,
  },

  // Cluster 3: Identity, Tenants & Config (Indigo)
  {
    id: "access",
    pccCode: "PCC-03",
    title: "Identity & Access Governance",
    shortTitle: "Access & IAM",
    description: "Role-based access matrix, OIDC federations, session management, and SCIM directory syncing.",
    href: "/access",
    cluster: "iam",
    clusterName: "Identity, Tenants & Config",
    accentVar: "var(--pcc-accent-iam)",
    accentHoverVar: "var(--pcc-accent-iam-hover)",
    accentSubtleVar: "var(--pcc-accent-iam-subtle)",
    accentGlowVar: "var(--pcc-accent-iam-glow)",
    permission: "pcc.iam.view",
    shortcut: "I",
    icon: PccIamIcon,
  },
  {
    id: "tenants",
    pccCode: "PCC-18",
    title: "Tenant Directory & Provisioning",
    shortTitle: "Tenants",
    description: "Enterprise customer directory, multi-region database provisioning, and tenant lifecycle audit.",
    href: "/tenants/directory",
    cluster: "iam",
    clusterName: "Identity, Tenants & Config",
    accentVar: "var(--pcc-accent-iam)",
    accentHoverVar: "var(--pcc-accent-iam-hover)",
    accentSubtleVar: "var(--pcc-accent-iam-subtle)",
    accentGlowVar: "var(--pcc-accent-iam-glow)",
    permission: "pcc.tenants.view",
    shortcut: "N",
    icon: PccTenantsIcon,
  },
  {
    id: "settings-features",
    pccCode: "PCC-13",
    title: "Feature Flags & Config",
    shortTitle: "Configuration",
    description: "Global runtime feature flags, environment config promotion, and tenant override rules.",
    href: "/settings/features",
    cluster: "iam",
    clusterName: "Identity, Tenants & Config",
    accentVar: "var(--pcc-accent-iam)",
    accentHoverVar: "var(--pcc-accent-iam-hover)",
    accentSubtleVar: "var(--pcc-accent-iam-subtle)",
    accentGlowVar: "var(--pcc-accent-iam-glow)",
    permission: "pcc.config.view",
    shortcut: "F",
    icon: PccConfigIcon,
  },

  // Cluster 4: Monetization & Licenses (Amber)
  {
    id: "subscriptions",
    pccCode: "PCC-04",
    title: "Subscription Operations",
    shortTitle: "Subscriptions",
    description: "Lifecycle states, plan upgrade/downgrade amendments, and contract renewal pipelines.",
    href: "/subscription-operations",
    cluster: "billing",
    clusterName: "Monetization & Licenses",
    accentVar: "var(--pcc-accent-billing)",
    accentHoverVar: "var(--pcc-accent-billing-hover)",
    accentSubtleVar: "var(--pcc-accent-billing-subtle)",
    accentGlowVar: "var(--pcc-accent-billing-glow)",
    permission: "pcc.subscriptions.view",
    shortcut: "U",
    icon: PccSubscriptionsIcon,
  },
  {
    id: "entitlements",
    pccCode: "PCC-05",
    title: "Entitlement Authority",
    shortTitle: "Entitlements",
    description: "Cryptographic seat pools, module feature grants, and offline air-gapped activation keys.",
    href: "/entitlement-authority",
    cluster: "billing",
    clusterName: "Monetization & Licenses",
    accentVar: "var(--pcc-accent-billing)",
    accentHoverVar: "var(--pcc-accent-billing-hover)",
    accentSubtleVar: "var(--pcc-accent-billing-subtle)",
    accentGlowVar: "var(--pcc-accent-billing-glow)",
    permission: "pcc.entitlements.view",
    shortcut: "E",
    icon: PccEntitlementsIcon,
  },
  {
    id: "billing",
    pccCode: "PCC-06",
    title: "Billing & Revenue",
    shortTitle: "Billing",
    description: "Pricing tier catalog, invoicing ledger, Stripe gateway synchronization, and dunning rules.",
    href: "/billing",
    cluster: "billing",
    clusterName: "Monetization & Licenses",
    accentVar: "var(--pcc-accent-billing)",
    accentHoverVar: "var(--pcc-accent-billing-hover)",
    accentSubtleVar: "var(--pcc-accent-billing-subtle)",
    accentGlowVar: "var(--pcc-accent-billing-glow)",
    permission: "pcc.billing.view",
    shortcut: "B",
    icon: PccBillingIcon,
  },

  // Cluster 5: Ecosystem & Developer Tools (Purple)
  {
    id: "developers",
    pccCode: "PCC-14",
    title: "Developer Ecosystem",
    shortTitle: "Developers",
    description: "OAuth2 client registration, webhook endpoints, sandbox tenant provisioning, and SDK catalog.",
    href: "/developers",
    cluster: "dev",
    clusterName: "Ecosystem & Developer Tools",
    accentVar: "var(--pcc-accent-dev)",
    accentHoverVar: "var(--pcc-accent-dev-hover)",
    accentSubtleVar: "var(--pcc-accent-dev-subtle)",
    accentGlowVar: "var(--pcc-accent-dev-glow)",
    permission: "pcc.developers.view",
    shortcut: "V",
    icon: PccDevelopersIcon,
  },
  {
    id: "integrations",
    pccCode: "PCC-20",
    title: "Connectors & Integrations",
    shortTitle: "Integrations",
    description: "Visual schema field mapper, connector health matrix, sync scheduler, and webhook ingress.",
    href: "/integrations",
    cluster: "dev",
    clusterName: "Ecosystem & Developer Tools",
    accentVar: "var(--pcc-accent-dev)",
    accentHoverVar: "var(--pcc-accent-dev-hover)",
    accentSubtleVar: "var(--pcc-accent-dev-subtle)",
    accentGlowVar: "var(--pcc-accent-dev-glow)",
    permission: "pcc.integrations.view",
    shortcut: "G",
    icon: PccIntegrationsIcon,
  },
  {
    id: "ai",
    pccCode: "PCC-21",
    title: "AI Models & Governance",
    shortTitle: "AI Governance",
    description: "Multi-LLM provider registry, safety guardrail policy editor, and token cost telemetry.",
    href: "/ai",
    cluster: "dev",
    clusterName: "Ecosystem & Developer Tools",
    accentVar: "var(--pcc-accent-dev)",
    accentHoverVar: "var(--pcc-accent-dev-hover)",
    accentSubtleVar: "var(--pcc-accent-dev-subtle)",
    accentGlowVar: "var(--pcc-accent-dev-glow)",
    permission: "pcc.ai.view",
    shortcut: "L",
    icon: PccAiIcon,
  },
  {
    id: "marketplace",
    pccCode: "PCC-17",
    title: "Extension Marketplace",
    shortTitle: "Marketplace",
    description: "Partner extension submission pipeline, review checklists, staged rollout, and killswitch.",
    href: "/marketplace",
    cluster: "dev",
    clusterName: "Ecosystem & Developer Tools",
    accentVar: "var(--pcc-accent-dev)",
    accentHoverVar: "var(--pcc-accent-dev-hover)",
    accentSubtleVar: "var(--pcc-accent-dev-subtle)",
    accentGlowVar: "var(--pcc-accent-dev-glow)",
    permission: "pcc.marketplace.view",
    shortcut: "X",
    icon: PccMarketplaceIcon,
  },
  {
    id: "mobile-operations",
    pccCode: "PCC-11",
    title: "Mobile Operations",
    shortTitle: "Mobile",
    description: "Fastlane CI pipeline grid, APNs/FCM push gateway, OTA distribution, and signing profiles.",
    href: "/mobile-operations",
    cluster: "dev",
    clusterName: "Ecosystem & Developer Tools",
    accentVar: "var(--pcc-accent-dev)",
    accentHoverVar: "var(--pcc-accent-dev-hover)",
    accentSubtleVar: "var(--pcc-accent-dev-subtle)",
    accentGlowVar: "var(--pcc-accent-dev-glow)",
    permission: "pcc.mobile.view",
    shortcut: "M",
    icon: PccMobileIcon,
  },

  // Cluster 6: Support, Learning & Analytics (Rose)
  {
    id: "support",
    pccCode: "PCC-22",
    title: "Support & Diagnostics",
    shortTitle: "Support",
    description: "Tier-3 escalation ticket split-view, cryptographic diagnostic consent, and session replay.",
    href: "/support",
    cluster: "support",
    clusterName: "Support, Learning & Analytics",
    accentVar: "var(--pcc-accent-support)",
    accentHoverVar: "var(--pcc-accent-support-hover)",
    accentSubtleVar: "var(--pcc-accent-support-subtle)",
    accentGlowVar: "var(--pcc-accent-support-glow)",
    permission: "pcc.support.view",
    shortcut: "P",
    icon: PccSupportIcon,
  },
  {
    id: "knowledge-adoption",
    pccCode: "PCC-15",
    title: "Knowledge & Adoption",
    shortTitle: "Knowledge",
    description: "Multi-lingual article editor, role-based learning tracks, and customer adoption metrics.",
    href: "/knowledge-adoption",
    cluster: "support",
    clusterName: "Support, Learning & Analytics",
    accentVar: "var(--pcc-accent-support)",
    accentHoverVar: "var(--pcc-accent-support-hover)",
    accentSubtleVar: "var(--pcc-accent-support-subtle)",
    accentGlowVar: "var(--pcc-accent-support-glow)",
    permission: "pcc.knowledge.view",
    shortcut: "W",
    icon: PccKnowledgeIcon,
  },
  {
    id: "analytics",
    pccCode: "PCC-16",
    title: "Platform Analytics",
    shortTitle: "Analytics",
    description: "Visual dashboard composer, recurring PDF/CSV report delivery scheduler, and anomaly telemetry.",
    href: "/analytics",
    cluster: "support",
    clusterName: "Support, Learning & Analytics",
    accentVar: "var(--pcc-accent-support)",
    accentHoverVar: "var(--pcc-accent-support-hover)",
    accentSubtleVar: "var(--pcc-accent-support-subtle)",
    accentGlowVar: "var(--pcc-accent-support-glow)",
    permission: "pcc.analytics.view",
    shortcut: "A",
    icon: PccAnalyticsIcon,
  },
];

export function getPccDomain(id: string): PccDomainEntry | undefined {
  return PCC_REGISTRY.find((d) => d.id === id || d.pccCode === id || d.href === id);
}

export function getPccDomainsByCluster(cluster: PccDomainCluster): PccDomainEntry[] {
  return PCC_REGISTRY.filter((d) => d.cluster === cluster);
}

export function searchPccDomains(query: string): PccDomainEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return PCC_REGISTRY;
  return PCC_REGISTRY.filter((d) =>
    d.title.toLowerCase().includes(q) ||
    d.shortTitle.toLowerCase().includes(q) ||
    d.pccCode.toLowerCase().includes(q) ||
    d.description.toLowerCase().includes(q) ||
    d.clusterName.toLowerCase().includes(q)
  );
}
